In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pnpreprocessor as preprocessor
%matplotlib inline

In [2]:
data = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')

In [3]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
features = data.iloc[:, [0,1,2,3]].values 
label  = data.iloc[:, 4].values 

In [5]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
features = sc.fit_transform(features)

In [6]:
from sklearn.decomposition import PCA
principalComponents = PCA(n_components = 2)   # here no of components should not be greater than no. of features so another trick
principalComponents.fit(features,label)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [7]:
principalComponents.explained_variance_ratio_

array([0.72770452, 0.23030523])

In [8]:
finalFeatures = principalComponents.transform(features)

In [9]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(finalFeatures,label)

C:\Users\KiranThakur\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\KiranThakur\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [10]:
model.score(finalFeatures,label)

0.8666666666666667

In [11]:
principalComponents.components_

array([[ 0.52237162, -0.26335492,  0.58125401,  0.56561105],
       [ 0.37231836,  0.92555649,  0.02109478,  0.06541577]])

In [12]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [13]:
pd.DataFrame(principalComponents.components_ , columns=data.columns[0:4], index =["PC1", "PC2"])

sepal_length  sepal_width  petal_length  petal_width
PC1      0.522372    -0.263355      0.581254     0.565611
PC2      0.372318     0.925556      0.021095     0.065416

In [16]:
# Deploy Idea - 

sepal_length = float(input("Enter Sepal length: "))
sepal_width = float(input("Enter Sepal width: "))
petal_length = float(input("Enter Petal length: "))
petal_width = float(input("Enter Petal width: "))

#Create Features - 
features = np.array([[sepal_length,sepal_width,petal_length, petal_width]])

#Scale Features -
features = sc.transform(features)

#Get Principal Components
finalFeatures = principalComponents.transform(features)

#Predict by Model -
print("This iris flower of the class is: ",model.predict(finalFeatures))

Enter Sepal length: 5.1
Enter Sepal width: 3.5
Enter Petal length: 1.4
Enter Petal width: 0.2
This iris flower of the class is:  ['setosa']


In [19]:
finalFeatures

array([[-2.26454173,  0.5057039 ]])