In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('C:\\Users\\KiranThakur\\Simplilearn_Scripts\\Prashant_Nair\\ML Project 1\\data.csv')

In [3]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284341   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.705587   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.884000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null int64
NOX        506 non-null float64
RM         501 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null int64
TAX        506 non-null int64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
MEDV       506 non-null float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [6]:
data[data.RM.isna()]

CRIM    ZN  INDUS  CHAS    NOX  RM   AGE     DIS  RAD  TAX  PTRATIO  \
10   0.22489  12.5   7.87     0  0.524 NaN  94.3  6.3467    5  311     15.2   
35   0.06417   0.0   5.96     0  0.499 NaN  68.2  3.3603    5  279     19.2   
63   0.12650  25.0   5.13     0  0.453 NaN  43.4  7.9809    8  284     19.7   
96   0.11504   0.0   2.89     0  0.445 NaN  69.6  3.4952    2  276     18.0   
135  0.55778   0.0  21.89     0  0.624 NaN  98.2  2.1107    4  437     21.2   

          B  LSTAT  MEDV  
10   392.52  20.45  15.0  
35   396.90   9.68  18.9  
63   395.58   9.50  25.0  
96   391.83  11.34  21.4  
135  394.67  16.96  18.1

In [7]:
data.RM.fillna(data.RM.median(), inplace = True)

In [8]:
data[data.RM.isna()]

Empty DataFrame
Columns: [CRIM, ZN, INDUS, CHAS, NOX, RM, AGE, DIS, RAD, TAX, PTRATIO, B, LSTAT, MEDV]
Index: []

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null int64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null int64
TAX        506 non-null int64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
MEDV       506 non-null float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [10]:
features = data.iloc[:,:-1].values
features

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [11]:
label = data.iloc[:,[-1]].values
label

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2],
       [28.7],
       [22.9],
       [27.1],
       [16.5],
       [18.9],
       [15. ],
       [18.9],
       [21.7],
       [20.4],
       [18.2],
       [19.9],
       [23.1],
       [17.5],
       [20.2],
       [18.2],
       [13.6],
       [19.6],
       [15.2],
       [14.5],
       [15.6],
       [13.9],
       [16.6],
       [14.8],
       [18.4],
       [21. ],
       [12.7],
       [14.5],
       [13.2],
       [13.1],
       [13.5],
       [18.9],
       [20. ],
       [21. ],
       [24.7],
       [30.8],
       [34.9],
       [26.6],
       [25.3],
       [24.7],
       [21.2],
       [19.3],
       [20. ],
       [16.6],
       [14.4],
       [19.4],
       [19.7],
       [20.5],
       [25. ],
       [23.4],
       [18.9],
       [35.4],
       [24.7],
       [31.6],
       [23.3],
       [19.6],
       [18.7],
       [16. ],
       [22.2],
       [25. ],
       [33. ],
       [23.5],
       [19

In [12]:
print(features.shape)
print(label.shape)

(506, 13)
(506, 1)


In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features,
                                                    label, 
                                                    test_size=0.2, 
                                                    random_state=85)

In [14]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [15]:
model.score(X_train, y_train)

0.7155344516129927

In [16]:
model.score(X_test, y_test)

0.8296263045500001

In [17]:
#Applying K-NN Assuming k = 3
from sklearn.neighbors import KNeighborsRegressor
model2 = KNeighborsRegressor(n_neighbors=11,
                             metric='minkowski',
                             p = 2)
model2.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=11)

In [18]:
model2.score(X_train, y_train)

0.5443628422685274

In [19]:
model2.score(X_test, y_test)

0.5731949747618788

In [20]:
from sklearn.tree import DecisionTreeRegressor
model3 = DecisionTreeRegressor()
model3.fit(X_train,y_train)

DecisionTreeRegressor()

In [21]:
model3.score(X_train, y_train)

1.0

In [22]:
model3.score(X_test, y_test)

0.8377543409775406

In [23]:
from sklearn.ensemble import RandomForestRegressor
model4 = RandomForestRegressor()
model4.fit(X_train,y_train)

C:\Users\KiranThakur\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor()

In [24]:
model4.score(X_train,y_train)

0.9825056993401229

In [25]:
model4.score(X_test, y_test)

0.9110535325664526

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

algo = LinearRegression()
cross_val_score(algo,features,label,cv=10)

array([ 0.73083242,  0.46196597, -1.00708331,  0.64005701,  0.54616501,
        0.73504795,  0.38318019, -0.13229552, -0.76574791,  0.41722728])

In [27]:
# Fold Validation Technique
# K-fold cross validation technique

from sklearn.linear_model import LinearRegression

model5 = LinearRegression()

from sklearn.model_selection import KFold

kfold = KFold(n_splits = 10,
             shuffle = True, # shuffle=True mean randomely records will be selected
             random_state = 1)

i=0
for train,test in kfold.split(features):
    i=i+1
    X_train,X_test = features[train],features[test]
    y_train,y_test = label[train],label[test]
    model5.fit(X_train,y_train)
    print('Training score is {} and Testing score is {} for Sample Spilt {}'
          .format(model.score(X_train,y_train),model5.score(X_test,y_test),i))

Training score is 0.7325627200890091 and Testing score is 0.7785225723752252 for Sample Spilt 1
Training score is 0.7331582860392547 and Testing score is 0.7655297349673833 for Sample Spilt 2
Training score is 0.7240609167638119 and Testing score is 0.8728255646463455 for Sample Spilt 3
Training score is 0.763041119560995 and Testing score is 0.4398134922706023 for Sample Spilt 4
Training score is 0.7268051262313489 and Testing score is 0.8470279383642924 for Sample Spilt 5
Training score is 0.7380125240337316 and Testing score is 0.7092143581457626 for Sample Spilt 6
Training score is 0.7374536008779178 and Testing score is 0.7211192222723852 for Sample Spilt 7
Training score is 0.7507248767300158 and Testing score is 0.5944608570674628 for Sample Spilt 8
Training score is 0.7407830536411056 and Testing score is 0.6982986432280185 for Sample Spilt 9
Training score is 0.7340689931218201 and Testing score is 0.7562395778454395 for Sample Spilt 10


In [28]:
from sklearn.model_selection import KFold

kfold = KFold(n_splits = 10,
             shuffle = True, # shuffle=True mean randomely records will be selected
             random_state = 1)

i=0
for train,test in kfold.split(features):
    i=i+1
    if i ==3:
        X_train_final,X_test_final,y_train_final,y_test_final = features[train],features[test],label[train],label[test]

In [29]:
from sklearn.linear_model import LinearRegression

finalModel = LinearRegression()
finalModel.fit(X_train_final,y_train_final)

LinearRegression()

In [30]:
finalModel.score(X_train_final,y_train_final)

0.725915441235989

In [31]:
finalModel.score(X_test_final,y_test_final)

0.8728255646463455

In [32]:
# #Create Features -
# features = np.array([[-5.43942006, 4.12628155, -1.6165014, -0.67288841, -1.42262747,
#        -11.44443979304, -49.31238772,  7.61111401, -26.0016879 , -0.5778192 ,
#        -0.97491834,  0.41164221, -66.86091034]])


# #Predict by Model -
# print("The price (MEDV) will be: ",finalModel.predict(features))

In [33]:
# #Create Features -
# features = np.array([[0.00632, 18, 2.31, 0, 0.538,
#        6.575, 65.2,  4.09, 1, 296,
#        15.3,  396.9, 4.98]])


# #Predict by Model -
# print("The price (MEDV) will be: ",finalModel.predict(features))

In [34]:
from sklearn.preprocessing import MinMaxScaler

scale= MinMaxScaler(feature_range=(-1,1))
features = scale.fit_transform(features)
features

array([[-1.        , -0.64      , -0.8643695 , ..., -0.42553191,
         1.        , -0.82064018],
       [-0.99952815, -1.        , -0.51539589, ...,  0.10638298,
         1.        , -0.5910596 ],
       [-0.9995286 , -1.        , -0.51539589, ...,  0.10638298,
         0.97947451, -0.87306843],
       ...,
       [-0.99877622, -1.        , -0.15909091, ...,  0.78723404,
         1.        , -0.78421634],
       [-0.99767854, -1.        , -0.15909091, ...,  0.78723404,
         0.98260124, -0.73785872],
       [-0.99907632, -1.        , -0.15909091, ...,  0.78723404,
         1.        , -0.66059603]])

In [35]:
print(features.shape)
print(label.shape)

(506, 13)
(506, 1)


In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features,
                                                    label, 
                                                    test_size=0.2, 
                                                    random_state=85)

In [37]:
from sklearn.linear_model import LinearRegression
finalmodel1 = LinearRegression()
finalmodel1.fit(X_train, y_train)

LinearRegression()

In [38]:
finalmodel1.score(X_train,y_train)

0.7155344516129927

In [39]:
finalmodel1.score(X_test,y_test)

0.8296263045499991

In [40]:
from sklearn.svm import SVR  #Support Vector Classifier & SVC is the support vector machine algorithm fot the multiclass 

finalmodel2 = SVR(kernel='rbf',gamma='auto') #Best practice is to set Gamma inbetween 0 to 1 & rbf=radial bais function
finalmodel2.fit(X_train,y_train)

C:\Users\KiranThakur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR(gamma='auto')

In [41]:
finalmodel2.score(X_train,y_train)

0.5141773738445675

In [42]:
finalmodel2.score(X_test,y_test)

0.6212842655214726

In [43]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
features = sc.fit_transform(features)

In [44]:
from sklearn.decomposition import PCA
principalComponents = PCA(n_components = 11)   # here no of components should not be greater than no. of features so another trick
principalComponents.fit(features,label)

PCA(n_components=11)

In [45]:
principalComponents.explained_variance_ratio_

array([0.47124644, 0.11029527, 0.0956676 , 0.06600537, 0.06423805,
       0.05057238, 0.04118756, 0.03040547, 0.02130442, 0.0168738 ,
       0.01432064])

In [46]:
finalFeatures = principalComponents.transform(features)

In [47]:
from sklearn.linear_model import LinearRegression

modelpca = LinearRegression()
modelpca.fit(finalFeatures,label)

LinearRegression()

In [48]:
modelpca.score(finalFeatures,label)

0.7121567643434552

In [49]:
from sklearn.metrics import mean_squared_error
housing_predictions = finalModel.predict(X_train_final)
mse = mean_squared_error(y_train_final, housing_predictions)
rmse = np.sqrt(mse)

In [50]:
rmse

4.835861890167238