In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('C:\\Users\\KiranThakur\\Simplilearn_Scripts\\Prashant_Nair\\ML Project 1\\data.csv')

In [3]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
data.RM.fillna(data.RM.median(), inplace = True)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null int64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null int64
TAX        506 non-null int64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
MEDV       506 non-null float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [6]:
features = data.iloc[:,:-1].values
features

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [7]:
features.shape

(506, 13)

In [8]:
label = data.iloc[:,[-1]].values
label

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2],
       [28.7],
       [22.9],
       [27.1],
       [16.5],
       [18.9],
       [15. ],
       [18.9],
       [21.7],
       [20.4],
       [18.2],
       [19.9],
       [23.1],
       [17.5],
       [20.2],
       [18.2],
       [13.6],
       [19.6],
       [15.2],
       [14.5],
       [15.6],
       [13.9],
       [16.6],
       [14.8],
       [18.4],
       [21. ],
       [12.7],
       [14.5],
       [13.2],
       [13.1],
       [13.5],
       [18.9],
       [20. ],
       [21. ],
       [24.7],
       [30.8],
       [34.9],
       [26.6],
       [25.3],
       [24.7],
       [21.2],
       [19.3],
       [20. ],
       [16.6],
       [14.4],
       [19.4],
       [19.7],
       [20.5],
       [25. ],
       [23.4],
       [18.9],
       [35.4],
       [24.7],
       [31.6],
       [23.3],
       [19.6],
       [18.7],
       [16. ],
       [22.2],
       [25. ],
       [33. ],
       [23.5],
       [19

# Method 1 - Using RFE (Recursive Feature Elimination)

In [9]:
#Step 1 Initialize the algoritham
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [10]:
#Step 2 Apply RFE
from sklearn.feature_selection import RFE
selectFeatures = RFE(estimator =model,step=1) #it will remove one feature at each iteration
selectFeatures.fit(features,label)
print(selectFeatures.support_)
print(selectFeatures.ranking_)

[False False False  True  True  True False  True False False  True False
  True]
[3 5 4 1 1 1 8 1 2 6 1 7 1]


In [11]:
# Initalize the algoritham
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [12]:
# Apply feature selection by Model

from sklearn.feature_selection import SelectFromModel
selectFeature = SelectFromModel(model)
selectFeature.fit(features,label)
finalFeaturesSelectByModel = selectFeature.transform(features)
print('Original lengh of features was {} and Model selected {}'.format(features.shape,finalFeaturesSelectByModel.shape))
print(selectFeature.get_support())

Original lengh of features was (506, 13) and Model selected (506, 3)
[False False False  True  True  True False False False False False False
 False]


In [13]:
# Step 1 - Initialize the algoritham
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [14]:
# Step 2 - Check using ANOVA
from sklearn.feature_selection import SelectPercentile
from sklearn.feature_selection import f_regression
selectFeatures = SelectPercentile(percentile=50, score_func=f_regression)
selectFeatures.fit(features,label)
finalFeaturesANOVA = selectFeatures.transform(features)
print('Orignal lenth of features was {} and Model selected {}'.format(features.shape,finalFeaturesANOVA.shape))
print(selectFeatures.get_support())

Orignal lenth of features was (506, 13) and Model selected (506, 6)
[False False  True False  True  True False False False  True  True False
  True]


C:\Users\KiranThakur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [15]:
# Bagging for LinearRegression 

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import RandomForestRegressor

algo = LinearRegression()
algoKNN = KNeighborsRegressor()
algoRandom = RandomForestRegressor()

RegressorBag = BaggingRegressor(base_estimator=algo,
    n_estimators=101,
    random_state=1)



RegressorKNNBag = BaggingRegressor(base_estimator=algoKNN,
    n_estimators=101,
    random_state=1)

RegressorRF = BaggingRegressor(base_estimator=algoRandom,
    n_estimators=101,
    random_state=1)

RegressorBag.fit(features,label)
RegressorKNNBag.fit(features,label)
RegressorRF.fit(features,label)

C:\Users\KiranThakur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\KiranThakur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\KiranThakur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


BaggingRegressor(base_estimator=RandomForestRegressor(), n_estimators=101,
                 random_state=1)

In [16]:
RegressorBag.score(features,label)

0.7400040955321118

In [17]:
RegressorRF.score(features,label)

0.953195419776719

In [18]:
RegressorKNNBag.score(features,label)

0.7305285897578123

In [19]:
from sklearn.metrics import mean_squared_error
housing_predictions = RegressorRF.predict(features)
mse = mean_squared_error(label, housing_predictions)
rmse = np.sqrt(mse)
rmse

1.9877680670855518

In [20]:
# #Create Features -
# features = np.array([[-5.43942006, 4.12628155, -1.6165014, -0.67288841, -1.42262747,
#        -11.44443979304, -49.31238772,  7.61111401, -26.0016879 , -0.5778192 ,
#        -0.97491834,  0.41164221, -66.86091034]])


# #Predict by Model -
# print("The price (MEDV) will be: ",RegressorRF.predict(features))

In [21]:
# Boosing for LogistincReggression 

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import RandomForestRegressor

algoLR = LinearRegression()
algoLRKNN = KNeighborsRegressor()
algoLRRandom = RandomForestRegressor()

boosterLR = AdaBoostRegressor(base_estimator=algoLR,
    n_estimators=101,
    random_state=1)

boosterLRKNN = AdaBoostRegressor(base_estimator=algoLRKNN,
    n_estimators=101,
    random_state=1)

boosterLRRandom = AdaBoostRegressor(base_estimator=algoLRRandom,
    n_estimators=101,
    random_state=1)

boosterLR.fit(features,label)
boosterLRKNN.fit(features,label)
boosterLRRandom.fit(features,label)

C:\Users\KiranThakur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\KiranThakur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\KiranThakur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


AdaBoostRegressor(base_estimator=RandomForestRegressor(), n_estimators=101,
                  random_state=1)

In [22]:
boosterLR.score(features,label)

0.7105883022748611

In [23]:
boosterLRKNN.score(features,label)

0.880697594431185

In [24]:
boosterLRRandom.score(features,label)

0.9943536536430265

In [25]:
# #Create Features -
# features = np.array([[-5.43942006, 4.12628155, -1.6165014, -0.67288841, -1.42262747,
#        -11.44443979304, -49.31238772,  7.61111401, -26.0016879 , -0.5778192 ,
#        -0.97491834,  0.41164221, -66.86091034]])


# #Predict by Model -
# print("The price (MEDV) will be: ",boosterLRRandom.predict(features))

In [26]:
features = np.append(np.ones((506,1)).astype(int), features, axis=1) # axis 1 is Column

In [27]:
features.shape

(506, 14)

In [28]:
features[0]

array([1.000e+00, 6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01,
       6.575e+00, 6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01,
       3.969e+02, 4.980e+00])

In [29]:
import statsmodels.api as sm
# Creating an OLS model .....LinearRegressionModel
# Step 1 -- All in (Pass all the feature variable available along with the label)
# endog ------> label and exog ---- > features
# Iteration 1:
model1 = sm.OLS(endog=label, exog=features).fit() #to create equation
model1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.740
Model:                            OLS   Adj. R-squared:                  0.733
Method:                 Least Squares   F-statistic:                     107.8
Date:                Thu, 14 May 2020   Prob (F-statistic):          1.13e-134
Time:                        00:33:48   Log-Likelihood:                -1499.3
No. Observations:                 506   AIC:                             3027.
Df Residuals:                     492   BIC:                             3086.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.4697      5.124      7.117      0.000      26.401      46.538
x1            -0.1081      0.033     -3.285      0.001      -0.173      -0.043
x2             0.0464      0.014      3.375      0.001       0.019       0.073
x3             0.0220      0.062      0.357      0.721      -0.099       0.143
x4             2.6844      0.863      3.112      0.002       0.990       4.379
x5           -17.7231      3.824     -4.634      0.000     -25.237     -10.209
x6             3.7971      0.420      9.049      0.000       2.973       4.622
x7             0.0011      0.013      0.080      0.937      -0.025       0.027
x8            -1.4633      0.200     -7.321      0.000      -1.856      -1.071
x9             0.3077      0.066      4.634      0.000       0.177       0.438
x10           -0.0124      0.004     -3.302      0.001      -0.020      -0.005
x11           -0.9533      0.131     -7.279      0.000      -1.211      -0.696
x12            0.0093      0.003      3.467      0.001       0.004       0.015
x13           -0.5253      0.051    -10.336      0.000      -0.625      -0.425
==============================================================================
Omnibus:                      177.283   Durbin-Watson:                   1.077
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              774.232
Skew:                           1.516   Prob(JB):                    7.55e-169
Kurtosis:                       8.247   Cond. No.                     1.51e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.51e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [30]:
#Iteration 2
newFeatures1 =features[:,[0,1,2,3,4,5,6,8,9,10,11,12,13]]
model1 = sm.OLS(endog=label, exog=newFeatures1).fit() #to create equation
model1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.740
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     117.0
Date:                Thu, 14 May 2020   Prob (F-statistic):          1.02e-135
Time:                        00:33:48   Log-Likelihood:                -1499.3
No. Observations:                 506   AIC:                             3025.
Df Residuals:                     493   BIC:                             3080.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.4355      5.101      7.143      0.000      26.413      46.458
x1            -0.1081      0.033     -3.289      0.001      -0.173      -0.044
x2             0.0463      0.014      3.394      0.001       0.019       0.073
x3             0.0220      0.062      0.357      0.721      -0.099       0.143
x4             2.6879      0.861      3.124      0.002       0.997       4.379
x5           -17.6423      3.684     -4.789      0.000     -24.880     -10.405
x6             3.8040      0.410      9.272      0.000       2.998       4.610
x7            -1.4679      0.191     -7.681      0.000      -1.843      -1.092
x8             0.3073      0.066      4.646      0.000       0.177       0.437
x9            -0.0124      0.004     -3.304      0.001      -0.020      -0.005
x10           -0.9525      0.130     -7.302      0.000      -1.209      -0.696
x11            0.0093      0.003      3.482      0.001       0.004       0.015
x12           -0.5240      0.048    -10.975      0.000      -0.618      -0.430
==============================================================================
Omnibus:                      177.739   Durbin-Watson:                   1.076
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              779.114
Skew:                           1.519   Prob(JB):                    6.57e-170
Kurtosis:                       8.265   Cond. No.                     1.49e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.49e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [31]:
#Iteration 3
newFeatures2 =features[:,[0,1,2,4,5,6,8,9,10,11,12,13]]
model1 = sm.OLS(endog=label, exog=newFeatures2).fit() #to create equation
model1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.740
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     127.8
Date:                Thu, 14 May 2020   Prob (F-statistic):          9.41e-137
Time:                        00:33:48   Log-Likelihood:                -1499.4
No. Observations:                 506   AIC:                             3023.
Df Residuals:                     494   BIC:                             3074.
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.3379      5.089      7.140      0.000      26.338      46.337
x1            -0.1085      0.033     -3.307      0.001      -0.173      -0.044
x2             0.0457      0.014      3.378      0.001       0.019       0.072
x3             2.7196      0.855      3.180      0.002       1.039       4.400
x4           -17.2820      3.540     -4.882      0.000     -24.237     -10.327
x5             3.7898      0.408      9.289      0.000       2.988       4.591
x6            -1.4830      0.186     -7.966      0.000      -1.849      -1.117
x7             0.3007      0.063      4.738      0.000       0.176       0.425
x8            -0.0118      0.003     -3.505      0.000      -0.018      -0.005
x9            -0.9465      0.129     -7.324      0.000      -1.200      -0.693
x10            0.0093      0.003      3.475      0.001       0.004       0.015
x11           -0.5226      0.048    -10.991      0.000      -0.616      -0.429
==============================================================================
Omnibus:                      177.820   Durbin-Watson:                   1.076
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              780.440
Skew:                           1.519   Prob(JB):                    3.38e-170
Kurtosis:                       8.271   Cond. No.                     1.47e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.47e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [32]:
newFeatures2[0]

array([1.000e+00, 6.320e-03, 1.800e+01, 0.000e+00, 5.380e-01, 6.575e+00,
       4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02, 4.980e+00])

In [33]:
from sklearn.model_selection import train_test_split
X_train_final, X_test_final, y_train_final, y_test_final =train_test_split(newFeatures2,label,test_size=0.2,random_state=95)

In [34]:
from sklearn.linear_model import LinearRegression
finalmodel = LinearRegression()
finalmodel.fit(X_train_final,y_train_final)

LinearRegression()

In [35]:
finalmodel.score(X_train_final,y_train_final)

0.7198967323542137

In [36]:
finalmodel.score(X_test_final,y_test_final)

0.8013119128106251

In [37]:
#Create Features -
features = np.array([[1, -5.43942006, 4.12628155, -0.67288841, -1.42262747,
       -11.44443979304,  7.61111401, -26.0016879 , -0.5778192 ,
       -0.97491834,  0.41164221, -66.86091034]])


#Predict by Model -
print("The price (MEDV) will be: ",finalmodel.predict(features))

The price (MEDV) will be:  [[49.01660922]]


In [38]:
from sklearn.metrics import mean_squared_error
housing_predictions = finalmodel.predict(X_train_final)
mse = mean_squared_error(y_train_final, housing_predictions)
rmse = np.sqrt(mse)
rmse

4.8251374873579795